# -*- coding: utf-8 -*-
"""Heart-Disease-Deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NAOdfKXdVYH4ap8wcNPENkky4DAXQK80
"""

#!pip install streamlit
#!pip install joblib

import streamlit as st
import pandas as pd
import joblib

# Load trained model
model = joblib.load('heart_disease_pipeline.pkl')  # or logistic_regression_model.pkl

# Define input features
feature_names = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg',
                 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal']

st.title("Heart Disease Prediction App")

# User input
input_data = {}
for feature in feature_names:
    input_data[feature] = st.number_input(f"Enter {feature}", step=1.0)

# Convert to DataFrame
input_df = pd.DataFrame([input_data])

# Prediction
if st.button("Predict"):
    prediction = model.predict(input_df)[0]
    proba = model.predict_proba(input_df)[0][1]

    if prediction == 1:
        st.error(f"⚠️ High risk of heart disease ({proba:.2%} probability)")
    else:
        st.success(f"✅ Low risk of heart disease ({proba:.2%} probability)")